In [2]:
import pandas as pd

In [24]:
df = pd.read_csv('data1.csv')

In [4]:
df.shape

(16000, 16)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  str
 2   title         16000 non-null  str
 3   director      5035 non-null   str
 4   cast          14843 non-null  str
 5   country       14203 non-null  str
 6   date_added    16000 non-null  str
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   duration      16000 non-null  str
 10  genres        15026 non-null  str
 11  language      16000 non-null  str
 12  description   12794 non-null  str
 13  popularity    16000 non-null  float64
 14  vote_count    16000 non-null  int64
 15  vote_average  16000 non-null  float64
dtypes: float64(3), int64(3), str(10)
memory usage: 2.0 MB

In [6]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [7]:
df.tail(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.0,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.0
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.0,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.0
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.0,1 Seasons,Drama,it,NaN,2.913,1,10.0
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.0,1 Seasons,NaN,ko,NaN,2.787,0,0.0
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.0,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.0

In [8]:
pd.set_option('display.max_columns', 16)

In [9]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000

In [10]:
pd.set_option('display.max_rows', 20)

In [11]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000

In [12]:
df['release_year']

0        2010
1        2010
2        2010
3        2010
4        2010
         ...
15995    2025
15996    2025
15997    2025
15998    2025
15999    2025
Name: release_year, Length: 16000, dtype: int64

In [13]:
df['release_year'].value_counts()

release_year
2010    1000
2011    1000
2012    1000
2013    1000
2014    1000
2015    1000
2016    1000
2017    1000
2018    1000
2019    1000
2020    1000
2021    1000
2022    1000
2023    1000
2024    1000
2025    1000
Name: count, dtype: int64

In [19]:
df.loc[[0,1,2], ['release_year']]

   release_year
0          2010
1          2010
2          2010

In [18]:
df.loc[0]

show_id                                                     33238
type                                                      TV Show
title                                                 Running Man
director                                                      안재철
cast            Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...
country                                               South Korea
date_added                                             2010-07-11
release_year                                                 2010
rating                                                      8.241
duration                                                1 Seasons
genres                                            Comedy, Reality
language                                                       ko
description     A reality and competition show where members a...
popularity                                               1929.898
vote_count                                                    187
vote_average                                                8.241
Name: 0, dtype: object

In [20]:
df.loc[:, ['release_year']]

       release_year
0              2010
1              2010
2              2010
3              2010
4              2010
...             ...
15995          2025
15996          2025
15997          2025
15998          2025
15999          2025

[16000 rows x 1 columns]

In [22]:
df.loc[0:3, 'release_year':'language']

   release_year  rating   duration              genres language
0          2010   8.241  1 Seasons     Comedy, Reality       ko
1          2010   7.035  1 Seasons  Talk, Comedy, News       en
2          2010   5.600  1 Seasons             Reality       el
3          2010   6.500  1 Seasons             Reality       cs

In [23]:
df['language'].value_counts()

language
en    4437
zh    2456
ja    1883
ko    1364
es     916
      ...
pa       1
zu       1
az       1
km       1
mt       1
Name: count, Length: 71, dtype: int64