In [15]:
people = {
    'first': ["Chirag", "Sahil", "Yana"],
    'last': ["Arora", "Arora", "Bindal"],
    'email': ["chiragarora@email.com", "sahilarora@email.com", "yanabindal@email.com"],
    'count': [100, 101, 102]
}

In [16]:
people

{'first': ['Chirag', 'Sahil', 'Yana'],
 'last': ['Arora', 'Arora', 'Bindal'],
 'email': ['chiragarora@email.com',
  'sahilarora@email.com',
  'yanabindal@email.com'],
 'count': [100, 101, 102]}

In [17]:
people['email']

['chiragarora@email.com', 'sahilarora@email.com', 'yanabindal@email.com']

In [18]:
people['first']

['Chirag', 'Sahil', 'Yana']

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(people)

In [21]:
df

    first    last                  email  count
0  Chirag   Arora  chiragarora@email.com    100
1   Sahil   Arora   sahilarora@email.com    101
2    Yana  Bindal   yanabindal@email.com    102

In [22]:
df['email']

0    chiragarora@email.com
1     sahilarora@email.com
2     yanabindal@email.com
Name: email, dtype: str

In [23]:
df.email

0    chiragarora@email.com
1     sahilarora@email.com
2     yanabindal@email.com
Name: email, dtype: str

In [24]:
df['email']

0    chiragarora@email.com
1     sahilarora@email.com
2     yanabindal@email.com
Name: email, dtype: str

In [25]:
type(df['email'])

pandas.Series

In [26]:
type(df)

pandas.DataFrame

In [27]:
df[['last' , 'email']]

     last                  email
0   Arora  chiragarora@email.com
1   Arora   sahilarora@email.com
2  Bindal   yanabindal@email.com

In [28]:
df.count

<bound method DataFrame.count of     first    last                  email  count
0  Chirag   Arora  chiragarora@email.com    100
1   Sahil   Arora   sahilarora@email.com    101
2    Yana  Bindal   yanabindal@email.com    102>

In [29]:
df['count']

0    100
1    101
2    102
Name: count, dtype: int64

In [30]:
df.columns

Index(['first', 'last', 'email', 'count'], dtype='str')

In [31]:
df.iloc[0]

first                   Chirag
last                     Arora
email    chiragarora@email.com
count                      100
Name: 0, dtype: object

In [32]:
df.iloc[1]

first                   Sahil
last                    Arora
email    sahilarora@email.com
count                     101
Name: 1, dtype: object

In [33]:
df.iloc[[1,2]]

   first    last                 email  count
1  Sahil   Arora  sahilarora@email.com    101
2   Yana  Bindal  yanabindal@email.com    102

In [34]:
df.iloc[[1,2] , 2]

1    sahilarora@email.com
2    yanabindal@email.com
Name: email, dtype: str

In [35]:
df

    first    last                  email  count
0  Chirag   Arora  chiragarora@email.com    100
1   Sahil   Arora   sahilarora@email.com    101
2    Yana  Bindal   yanabindal@email.com    102

In [37]:
df.loc[0] # - right now same as iloc since there are no specific index labels, the indexes are just labeles : 0, 1, 2,.....

first                   Chirag
last                     Arora
email    chiragarora@email.com
count                      100
Name: 0, dtype: object

In [38]:
df.loc[[0,1]]

    first   last                  email  count
0  Chirag  Arora  chiragarora@email.com    100
1   Sahil  Arora   sahilarora@email.com    101

In [39]:
df.loc[[0,1], 'email']

0    chiragarora@email.com
1     sahilarora@email.com
Name: email, dtype: str

In [40]:
df.loc[[0,1], ['first', 'last']]

    first   last
0  Chirag  Arora
1   Sahil  Arora

In [45]:
df.loc[[0,1], ['last','first']]

    last   first
0  Arora  Chirag
1  Arora   Sahil

In [46]:
df

    first    last                  email  count
0  Chirag   Arora  chiragarora@email.com    100
1   Sahil   Arora   sahilarora@email.com    101
2    Yana  Bindal   yanabindal@email.com    102

In [55]:
df = df.reset_index()

In [56]:
df

                   email   first    last  count
0  chiragarora@email.com  Chirag   Arora    100
1   sahilarora@email.com   Sahil   Arora    101
2   yanabindal@email.com    Yana  Bindal    102

In [57]:
df.set_index('email')

                        first    last  count
email
chiragarora@email.com  Chirag   Arora    100
sahilarora@email.com    Sahil   Arora    101
yanabindal@email.com     Yana  Bindal    102

In [58]:
df

                   email   first    last  count
0  chiragarora@email.com  Chirag   Arora    100
1   sahilarora@email.com   Sahil   Arora    101
2   yanabindal@email.com    Yana  Bindal    102

In [59]:
df = df.set_index('email')

In [60]:
df

                        first    last  count
email
chiragarora@email.com  Chirag   Arora    100
sahilarora@email.com    Sahil   Arora    101
yanabindal@email.com     Yana  Bindal    102

In [64]:
df.reset_index(inplace = True)

In [62]:
df

                        first    last  count
email
chiragarora@email.com  Chirag   Arora    100
sahilarora@email.com    Sahil   Arora    101
yanabindal@email.com     Yana  Bindal    102

In [65]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [66]:
df.set_index('email', inplace= True)

In [67]:
df

                        first    last  count
email
chiragarora@email.com  Chirag   Arora    100
sahilarora@email.com    Sahil   Arora    101
yanabindal@email.com     Yana  Bindal    102

In [68]:
df.index

Index(['chiragarora@email.com', 'sahilarora@email.com',
       'yanabindal@email.com'],
      dtype='str', name='email')

In [70]:
df.loc[['sahilarora@email.com', 'yanabindal@email.com'], ['last']]

                        last
email
sahilarora@email.com   Arora
yanabindal@email.com  Bindal

In [71]:
df.loc['sahilarora@email.com', 'last']

'Arora'

In [72]:
df.loc[0]

KeyError: 0

In [73]:
df.iloc[0]

first    Chirag
last      Arora
count       100
Name: chiragarora@email.com, dtype: object

In [74]:
df.reset_index(inplace=True)
df

                   email   first    last  count
0  chiragarora@email.com  Chirag   Arora    100
1   sahilarora@email.com   Sahil   Arora    101
2   yanabindal@email.com    Yana  Bindal    102

In [75]:
df['last'] == 'Arora'

0     True
1     True
2    False
Name: last, dtype: bool

In [84]:
filt = ( df['last'] == 'Arora' )

In [85]:
filt

0     True
1     True
2    False
Name: last, dtype: bool

In [86]:
type(filt)

pandas.Series

In [87]:
df[filt]

                   email   first   last  count
0  chiragarora@email.com  Chirag  Arora    100
1   sahilarora@email.com   Sahil  Arora    101

In [88]:
df[df['last'] == 'Arora']

                   email   first   last  count
0  chiragarora@email.com  Chirag  Arora    100
1   sahilarora@email.com   Sahil  Arora    101

In [89]:
df.loc[filt]

                   email   first   last  count
0  chiragarora@email.com  Chirag  Arora    100
1   sahilarora@email.com   Sahil  Arora    101

In [90]:
df.loc[filt, 'count']

0    100
1    101
Name: count, dtype: int64

In [91]:
filt2 = (df['last'] == 'Arora') & (df['first'] == 'Sahil')

In [92]:
df.loc[filt2]

                  email  first   last  count
1  sahilarora@email.com  Sahil  Arora    101

In [93]:
filt3 = (df['last'] == 'Arora') | (df['first'] == 'Yana')

In [94]:
df.loc[filt3]

                   email   first    last  count
0  chiragarora@email.com  Chirag   Arora    100
1   sahilarora@email.com   Sahil   Arora    101
2   yanabindal@email.com    Yana  Bindal    102

In [95]:
df.loc[~filt3]

Empty DataFrame
Columns: [email, first, last, count]
Index: []