In [149]:
import pandas as pd
import numpy as np

In [150]:
df = pd.read_csv('netflix_titles.csv')

In [151]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [152]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [153]:
df.shape

(8807, 12)

In [154]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [155]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [156]:
filt = df['duration'].isnull()

In [157]:
df['rating'].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

In [158]:
filt = df['rating'].str.contains('min')

In [159]:
df.loc[filt, 'duration'] = df.loc[filt, 'rating']

In [160]:
df.loc[filt]['duration']

5541    74 min
5794    84 min
5813    66 min
Name: duration, dtype: str

In [161]:
df.loc[filt, 'rating'] = np.nan

In [162]:
df.loc[filt, 'rating']

5541    NaN
5794    NaN
5813    NaN
Name: rating, dtype: str

In [163]:
filt = df['rating'].isnull()
df.loc[filt]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,NaN,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,NaN,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,NaN,66 min,Movies,The comic puts his trademark hilarious/thought...
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [164]:
df.dropna(subset='rating', inplace=True)

In [165]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [166]:
filt = df['date_added'].isnull()
df.loc[filt]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [167]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country          830
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [168]:
# missing values in date_added, directors, case, do not matter much so we need not deal with them.
# our analysis will not be hampered due to these missing values

In [169]:
df['country'] = df['country'].fillna('unknown')

In [170]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2631
cast             825
country            0
date_added        10
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [171]:
df['title'].unique()

<StringArray>
[            'Dick Johnson Is Dead',                    'Blood & Water',
                        'Ganglands',            'Jailbirds New Orleans',
                     'Kota Factory',                    'Midnight Mass',
 'My Little Pony: A New Generation',                          'Sankofa',
    'The Great British Baking Show',                     'The Starling',
 ...
                        'Zak Storm',                         'Zed Plus',
                            'Zenda',               'Zindagi Gulzar Hai',
                          'Zinzana',                           'Zodiac',
                      'Zombie Dumb',                       'Zombieland',
                             'Zoom',                           'Zubaan']
Length: 8800, dtype: str

In [172]:
df.shape

(8800, 12)

In [173]:
# no duplicates as there are 8800 unique titles which is equal to the total titles

In [174]:
df['rating'].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [175]:
df['listed_in'].unique()

<StringArray>
[                                                'Documentaries',
               'International TV Shows, TV Dramas, TV Mysteries',
 'Crime TV Shows, International TV Shows, TV Action & Adventure',
                                        'Docuseries, Reality TV',
        'International TV Shows, Romantic TV Shows, TV Comedies',
                            'TV Dramas, TV Horror, TV Mysteries',
                                      'Children & Family Movies',
              'Dramas, Independent Movies, International Movies',
                                  'British TV Shows, Reality TV',
                                              'Comedies, Dramas',
 ...
                               'Comedies, Dramas, Sports Movies',
         'Action & Adventure, Romantic Movies, Sci-Fi & Fantasy',
                        'Classic & Cult TV, TV Sci-Fi & Fantasy',
                           'Comedies, Cult Movies, LGBTQ Movies',
                     'Comedies, Horror Movies, Sci-Fi & Fantasy',
                   'Action & Adventure, Comedies, Horror Movies',
                  'Classic & Cult TV, Crime TV Shows, TV Dramas',
              'Action & Adventure, Documentaries, Sports Movies',
           'International Movies, LGBTQ Movies, Romantic Movies',
                                'Cult Movies, Dramas, Thrillers']
Length: 514, dtype: str

In [176]:
df['points'] = np.random.uniform(1.0, 10.0, size=[8800,1])

In [ ]:
def top_movies():
    global df
    filt = df['type'] == 'Movie'
    top_movies = df.loc[filt].nlargest(10, 'points')
    return top_movies

In [ ]:
def common_genres():
    global df
    return df['listed_in'].value_counts().head(5)

In [ ]:
def common_countries():
    global df
    return df['country'].value_counts().head(5)

In [ ]:
def average_per_genre():
    global df
    genre = input("Enter genre: ")
    filt = df['listed_in'].str.contains(genre)

    return df.loc[filt, 'points'].mean()

In [ ]:
def common_directors():
    global df
    return df['director'].value_counts().head(5)

In [182]:
df['duration'].unique()

<StringArray>
[   '90 min', '2 Seasons',  '1 Season',    '91 min',   '125 min', '9 Seasons',
   '104 min',   '127 min', '4 Seasons',    '67 min',
 ...
    '43 min',   '200 min',   '196 min',   '167 min',   '178 min',   '228 min',
    '18 min',   '205 min',   '201 min',   '191 min']
Length: 220, dtype: str

In [183]:
df['duration'] = df['duration'].str.replace('min', '', regex=False).str.strip()
df['duration'] = df['duration'].str.replace('Seasons', '', regex=False).str.strip()
df['duration'] = df['duration'].str.replace('Season', '', regex=False).str.strip()

In [184]:
df['duration'].unique()

<StringArray>
[ '90',   '2',   '1',  '91', '125',   '9', '104', '127',   '4',  '67',
 ...
  '43', '200', '196', '167', '178', '228',  '18', '205', '201', '191']
Length: 210, dtype: str

In [185]:
df['duration'] = df['duration'].astype(float)

In [ ]:
def mean_runtime_by_country():
    global df
    country_grp = df.loc[df['type'] == 'Movie'].groupby('country')
    return country_grp['duration'].agg(['mean'])

In [ ]:
def year_wise_points():
    global df
    year_grp = df.groupby('release_year')
    year_mean = year_grp['points'].mean()
    return year_mean.sort_values(ascending=False, inplace=True)

In [ ]:
def runtime_by_genres_movie():
    global df
    genre_grp = df.loc[df['type'] == 'Movie'].groupby('listed_in')
    genre_points = genre_grp['duration'].mean()
    genre_points.sort_values(ascending=False, inplace=True)
    return genre_points

In [ ]:
def runtime_by_genres_show():
    global df
    genre_grp = df.loc[df['type'] == 'TV Show'].groupby('listed_in')
    genre_points = genre_grp['duration'].mean()
    genre_points.sort_values(ascending=False, inplace=True)
    return genre_points

In [ ]:
def runtime_rating_relation_movie():
    global df
    runtime = df.loc[df['type'] == 'Movie', 'duration']
    rating = df.loc[df['type'] == 'Movie', 'points']

    new_df = pd.concat([runtime, rating], axis=1)
    correlation = np.corrcoef(new_df['duration'] , new_df['points'])

    if abs(correlation[0,1]) > 0.70:
        return("The two are somewhat correlated")

    else: 
        return("The two are not related")

In [191]:
df['duration_hours'] = df['duration'] / 60

In [192]:
df.loc[df['type'] == 'TV Show' , 'duration_hours'] = np.nan

In [193]:
filt1 = ( (df['type'] == 'Movie') & (df['duration_hours'] > 2.5))
df.loc[filt1, 'category'] = 'long'

filt2 = ( (df['type'] == 'Movie') & (df['duration_hours'] <= 2.5) & (df['duration_hours'] >= 1.5) )
df.loc[filt2, 'category'] = 'medium'

filt3 = ( (df['type'] == 'Movie') & (df['duration_hours'] < 1.5))
df.loc[filt3, 'category'] = 'short'

filt4 = ( (df['type'] == 'TV Show') & (df['duration'] > 6))
df.loc[filt4, 'category'] = 'long'

filt5 = ( (df['type'] == 'TV Show') & (df['duration'] <= 6) & (df['duration'] >= 3) )
df.loc[filt5, 'category'] = 'medium'

filt6 = ( (df['type'] == 'TV Show') & (df['duration'] < 3))
df.loc[filt6, 'category'] = 'short'

In [194]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'points', 'duration_hours', 'category'],
      dtype='str')

In [195]:
def ranking_system():
    global df
    # points get 70% weightage in this ranking system.
    # release_year gets 10% weightage
    # category gets 10% weightage
    # country gets 10% weightage

    # these are kind of a bit senseless since i did not have much relevant columns to work with

    coin_points = df['points'] / 10 * 70
    
    df['coin_release_year'] = df['release_year']
    filt1 = (df['release_year'] > 2015)
    filt2 = (df['release_year'] > 2005) & (df['release_year'] <= 2015)
    filt3 = (df['release_year'] > 1995) & (df['release_year'] <= 2005)
    filt4 = (df['release_year'] > 1980) & (df['release_year'] <= 1995)
    filt5 = (df['release_year'] > 1970) & (df['release_year'] <= 1980)
    filt6 = (df['release_year'] <= 1970)

    df.loc[filt1, 'coin_release_year'] = 10
    df.loc[filt2, 'coin_release_year'] = 8
    df.loc[filt3, 'coin_release_year'] = 6
    df.loc[filt4, 'coin_release_year'] = 4
    df.loc[filt5, 'coin_release_year'] = 2
    df.loc[filt6, 'coin_release_year'] = 0


    coin_release_year = df['coin_release_year']
    df = df.drop('coin_release_year', axis=1)

    df['coin_category'] = df['category']
    df['coin_category'] = df['coin_category'].str.replace('medium', '10')
    df['coin_category'] = df['coin_category'].str.replace('long', '5')
    df['coin_category'] = df['coin_category'].str.replace('short', '5')
    
    df['coin_category'] = df['coin_category'].astype(float)

    coin_category = df['coin_category']
    df = df.drop('coin_category', axis=1) 

    df['coin_country'] = 0

    df.loc[df['country'] == 'India', 'coin_country'] = 10
    df.loc[df['country'] == 'United States of America', 'coin_country'] = 8
    df.loc[df['country'] == 'United Kingdom', 'coin_country'] = 6
    df.loc[df['country'] == 'Japan', 'coin_country'] = 4
    df.loc[df['country'] == 'South Korea', 'coin_country'] = 2

    coin_country = df['coin_country']
    df = df.drop('coin_country', axis=1)

    coins = coin_points + coin_category + coin_country

    df['coins'] = coins
    
    df.sort_values(by= 'coins', ascending=False, inplace=True)
    return df

In [196]:
df.isnull().sum()

show_id              0
type                 0
title                0
director          2631
cast               825
country              0
date_added          10
release_year         0
rating               0
duration             0
listed_in            0
description          0
points               0
duration_hours    2674
category             0
dtype: int64

In [202]:
ranking_system()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,points,duration_hours,category,coins
6439,s6440,Movie,Chal Dhar Pakad,Aatmaram Dharne,Nagesh Bhonsle,India,"March 15, 2018",2010,TV-14,129.0,"Comedies, Dramas, International Movies",After her fat-shaming husband brings home a ne...,9.999887,2.150000,medium,89.999210
7386,s7387,Movie,Maine Pyaar Kyun Kiya,David Dhawan,"Salman Khan, Sushmita Sen, Sohail Khan, Katrin...",India,"December 31, 2019",2005,TV-14,137.0,"Comedies, International Movies, Music & Musicals","After lying to his girlfriend, orthopedic surg...",9.985149,2.283333,medium,89.896043
4452,s4453,Movie,Mundeyan Ton Bachke Rahin,Navinder Pal Singh,"Roshan Prince, Jassi Gill, Simran Kaur Mundi, ...",India,"November 1, 2018",2014,TV-14,139.0,"Comedies, International Movies, Music & Musicals","When they both fall for the same girl, best pa...",9.971597,2.316667,medium,89.801180
7806,s7807,TV Show,Pyaar Tune Kya Kiya,NaN,"Meiyang Chang, Surbhi Jyoti",India,"June 1, 2017",2014,TV-14,3.0,"International TV Shows, Romantic TV Shows, TV ...",From teen lovers defying social and religious ...,9.960058,NaN,medium,89.720407
7475,s7476,Movie,Moh Maya Money,Munish Bhardwaj,"Ranvir Shorey, Neha Dhupia, Devendra Chowhan, ...",India,"May 1, 2017",2016,TV-MA,109.0,"Dramas, Independent Movies, International Movies",After investing in a shady deal that quickly f...,9.958595,1.816667,medium,89.710164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5379,s5380,Movie,Tom Segura: Completely Normal,Jay Chapman,Tom Segura,United States,"July 13, 2017",2014,TV-MA,74.0,Stand-Up Comedy,Levelheaded stand-up Tom Segura shares offhand...,1.011528,1.233333,short,12.080694
3404,s3405,TV Show,MONKART,NaN,"Kim Jae-ha, Kwon Ji-hye, Lee Bo-hee, Um Sang-h...",unknown,"October 18, 2019",2017,TV-Y7,1.0,"Kids' TV, Korean TV Shows",Jin and his dragon monster Draka set out on a ...,1.006925,NaN,short,12.048475
3953,s3954,TV Show,Kicko & Super Speedo,NaN,NaN,unknown,"April 1, 2019",2018,TV-Y7,1.0,"Kids' TV, TV Comedies",This high-energy animated series follows a gut...,1.006751,NaN,short,12.047258
3695,s3696,TV Show,Rabbids Invasion,NaN,"Damien Laquet, David Gasman, Barbara Scaff",France,"July 1, 2019",2018,TV-Y7,1.0,"Kids' TV, TV Comedies","Giant, rambunctious rabbits have invaded and a...",1.001759,NaN,short,12.012316
376,s377,TV Show,Transformers: War for Cybertron: Kingdom,NaN,"Jake Foushee, Jason Marnocha, Linsay Rousseau,...",unknown,"July 29, 2021",2021,TV-Y7,1.0,Anime Series,The frantic race to locate the Allspark first ...,1.001157,NaN,short,12.008101

In [203]:
new_df = df.head(10)

In [204]:
df.to_csv('netflix_cleaned.csv', index=False)

In [205]:
new_df.to_csv('top_movies_shows.csv', index=False)