In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('DailyDelhiClimateTest.csv')

In [22]:
df.shape

(114, 5)

In [23]:
df.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

In [24]:
type(df.loc[0, 'date'])

str

In [25]:
df['date'] = pd.to_datetime(df['date'])

In [26]:
type(df.loc[0, 'date'])

pandas.Timestamp

In [27]:
df.loc[0, 'date'].day_name()

'Sunday'

In [28]:
df.head()

        date   meantemp   humidity  wind_speed  meanpressure
0 2017-01-01  15.913043  85.869565    2.743478     59.000000
1 2017-01-02  18.500000  77.222222    2.894444   1018.277778
2 2017-01-03  17.111111  81.888889    4.016667   1018.333333
3 2017-01-04  18.700000  70.050000    4.545000   1015.700000
4 2017-01-05  18.388889  74.944444    3.300000   1014.333333

In [29]:
df['date']

0     2017-01-01
1     2017-01-02
2     2017-01-03
3     2017-01-04
4     2017-01-05
         ...
109   2017-04-20
110   2017-04-21
111   2017-04-22
112   2017-04-23
113   2017-04-24
Name: date, Length: 114, dtype: datetime64[us]

In [30]:
df['date'].dt.day_name()

0         Sunday
1         Monday
2        Tuesday
3      Wednesday
4       Thursday
         ...
109     Thursday
110       Friday
111     Saturday
112       Sunday
113       Monday
Name: date, Length: 114, dtype: str

In [31]:
df['day'] = df['date'].dt.day_name()

In [32]:
df

          date   meantemp   humidity  wind_speed  meanpressure        day
0   2017-01-01  15.913043  85.869565    2.743478     59.000000     Sunday
1   2017-01-02  18.500000  77.222222    2.894444   1018.277778     Monday
2   2017-01-03  17.111111  81.888889    4.016667   1018.333333    Tuesday
3   2017-01-04  18.700000  70.050000    4.545000   1015.700000  Wednesday
4   2017-01-05  18.388889  74.944444    3.300000   1014.333333   Thursday
..         ...        ...        ...         ...           ...        ...
109 2017-04-20  34.500000  27.500000    5.562500    998.625000   Thursday
110 2017-04-21  34.250000  39.375000    6.962500    999.875000     Friday
111 2017-04-22  32.900000  40.900000    8.890000   1001.600000   Saturday
112 2017-04-23  32.875000  27.500000    9.962500   1002.125000     Sunday
113 2017-04-24  32.000000  27.142857   12.157143   1004.142857     Monday

[114 rows x 6 columns]

In [36]:
df.set_index('date', inplace=True)

In [37]:
df.resample('W').agg({'humidity' : 'max', 'wind_speed' : 'mean'})

             humidity  wind_speed
date
2017-01-01  85.869565    2.743478
2017-01-08  95.833333    5.061371
2017-01-15  80.809524    6.806319
2017-01-22  84.444444    9.368017
2017-01-29  91.642857    8.815970
2017-02-05  78.625000    5.264149
2017-02-12  71.777778    6.182659
2017-02-19  70.750000    7.274209
2017-02-26  69.416667   11.535034
2017-03-05  58.375000    6.725928
2017-03-12  69.071429    8.423547
2017-03-19  59.700000    7.726709
2017-03-26  54.666667   10.151944
2017-04-02  40.666667   10.218594
2017-04-09  46.000000   10.904628
2017-04-16  37.625000    8.387557
2017-04-23  40.900000    7.654325
2017-04-30  27.142857   12.157143