In [46]:
import pandas as pd

In [47]:
stocks_df = pd.read_csv('Toyota_Stock_1980_2025.csv')

In [48]:
stocks_df.head()

         Date  Adj_Close     Close      High       Low      Open  Volume
0  1980-03-17   1.813283  3.291227  3.344743  3.291227  3.291227   41109
1  1980-03-18   1.820654  3.304606  3.358122  3.304606  3.304606    9343
2  1980-03-19   1.820654  3.304606  3.304606  3.304606  3.304606       0
3  1980-03-20   1.820654  3.304606  3.358122  3.304606  3.304606   10277
4  1980-03-21   1.864881  3.384880  3.438396  3.384880  3.384880    8409

In [49]:
type(stocks_df.loc[0, 'Date'])

str

In [50]:
stocks_df['Date'] = pd.to_datetime(stocks_df['Date'])

In [51]:
type(stocks_df.loc[0, 'Date'])

pandas.Timestamp

In [52]:
stocks_df.shape

(11542, 7)

In [53]:
stocks_df.set_index('Date', inplace=True)

In [54]:
stocks_df.shape

(11542, 6)

In [55]:
stocks_df.loc['1980-03-17' : '1981-03-16']

            Adj_Close     Close      High       Low      Open  Volume
Date
1980-03-17   1.813283  3.291227  3.344743  3.291227  3.291227   41109
1980-03-18   1.820654  3.304606  3.358122  3.304606  3.304606    9343
1980-03-19   1.820654  3.304606  3.304606  3.304606  3.304606       0
1980-03-20   1.820654  3.304606  3.358122  3.304606  3.304606   10277
1980-03-21   1.864881  3.384880  3.438396  3.384880  3.384880    8409
...               ...       ...       ...       ...       ...     ...
1981-03-10   2.337366  4.242472  4.270568  4.242472  4.242472    3559
1981-03-11   2.314149  4.200329  4.228424  4.200329  4.228424   10678
1981-03-12   2.314149  4.200329  4.228424  4.200329  4.200329   26694
1981-03-13   2.314149  4.200329  4.242472  4.200329  4.200329   13347
1981-03-16   2.461201  4.467239  4.481287  4.467239  4.467239   14237

[252 rows x 6 columns]

In [56]:
index_series = pd.Series(stocks_df.index)
days_series = index_series.dt.day_name()
days_series.index = index_series
stocks_df['Day'] = days_series

In [57]:
year_series = index_series.dt.year
year_series.index = index_series
stocks_df['Year'] = year_series

month_series = index_series.dt.month_name()
month_series.index = index_series
stocks_df['Month'] = month_series

In [58]:
stocks_df

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month
Date,,,,,,,,,
1980-03-17,1.813283,3.291227,3.344743,3.291227,3.291227,41109,Monday,1980,March
1980-03-18,1.820654,3.304606,3.358122,3.304606,3.304606,9343,Tuesday,1980,March
1980-03-19,1.820654,3.304606,3.304606,3.304606,3.304606,0,Wednesday,1980,March
1980-03-20,1.820654,3.304606,3.358122,3.304606,3.304606,10277,Thursday,1980,March
1980-03-21,1.864881,3.384880,3.438396,3.384880,3.384880,8409,Friday,1980,March
...,...,...,...,...,...,...,...,...,...
2025-12-23,219.240005,219.240005,219.509995,218.020004,218.880005,330500,Tuesday,2025,December
2025-12-24,216.729996,216.729996,217.029999,215.000000,215.699997,170800,Wednesday,2025,December
2025-12-26,216.619995,216.619995,217.139999,215.949997,216.380005,146000,Friday,2025,December
2025-12-29,216.440002,216.440002,216.669998,214.860001,215.669998,247100,Monday,2025,December
2025-12-30,214.850006,214.850006,216.100006,214.850006,215.880005,184500,Tuesday,2025,December

In [59]:
highest_alltime = stocks_df['High'].max()
print("The all time high for the stock is", highest_alltime)

The all time high for the stock is 255.2299957

In [60]:
lowest_alltime = stocks_df['Low'].min()
print("The all time low for the stock is", lowest_alltime)

The all time low for the stock is 3.237710953

In [61]:
stocks_df.loc['2015']

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month
Date,,,,,,,,,
2015-01-02,93.269127,125.669998,126.639999,124.889999,126.230003,250000,Friday,2015,January
2015-01-05,91.562134,123.370003,124.610001,123.050003,124.440002,240600,Monday,2015,January
2015-01-06,90.619560,122.099998,123.720001,121.209999,123.400002,285600,Tuesday,2015,January
2015-01-07,92.898033,125.169998,126.059998,125.059998,125.519997,385700,Wednesday,2015,January
2015-01-08,94.686684,127.580002,127.699997,126.449997,126.449997,498800,Thursday,2015,January
...,...,...,...,...,...,...,...,...,...
2015-12-24,95.993073,125.769997,126.110001,125.400002,125.400002,102300,Thursday,2015,December
2015-12-28,95.000847,124.470001,124.849998,124.230003,124.430000,283800,Monday,2015,December
2015-12-29,95.222191,124.760002,125.080002,124.089996,124.089996,160400,Tuesday,2015,December
2015-12-30,94.046799,123.220001,124.430000,123.110001,124.400002,334100,Wednesday,2015,December
2015-12-31,93.909409,123.040001,124.330002,122.650002,123.349998,221000,Thursday,2015,December

In [62]:
filt = (stocks_df['Month'] == 'March') | (stocks_df['Month'] == 'April') | (stocks_df['Month'] == 'May') | (stocks_df['Month'] == 'June')

In [63]:
stocks_df.loc[filt]

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month
Date,,,,,,,,,
1980-03-17,1.813283,3.291227,3.344743,3.291227,3.291227,41109,Monday,1980,March
1980-03-18,1.820654,3.304606,3.358122,3.304606,3.304606,9343,Tuesday,1980,March
1980-03-19,1.820654,3.304606,3.304606,3.304606,3.304606,0,Wednesday,1980,March
1980-03-20,1.820654,3.304606,3.358122,3.304606,3.304606,10277,Thursday,1980,March
1980-03-21,1.864881,3.384880,3.438396,3.384880,3.384880,8409,Friday,1980,March
...,...,...,...,...,...,...,...,...,...
2025-06-24,171.580002,171.580002,172.389999,171.509995,171.800003,400200,Tuesday,2025,June
2025-06-25,169.149994,169.149994,170.029999,169.070007,169.919998,468400,Wednesday,2025,June
2025-06-26,170.630005,170.630005,170.910004,169.619995,170.100006,335400,Thursday,2025,June
2025-06-27,175.740005,175.740005,176.720001,174.899994,175.479996,513000,Friday,2025,June
2025-06-30,172.259995,172.259995,173.520004,171.699997,172.679993,521900,Monday,2025,June

In [64]:
stocks_df.loc['2025-01-01' : '2025-12-31']

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month
Date,,,,,,,,,
2025-01-02,189.391754,193.119995,194.800003,192.000000,194.399994,615500,Thursday,2025,January
2025-01-03,191.480637,195.250000,195.500000,193.229996,194.190002,611300,Friday,2025,January
2025-01-06,186.714462,190.389999,193.270004,189.839996,193.000000,664400,Monday,2025,January
2025-01-07,189.391754,193.119995,194.970001,192.419998,194.589996,585500,Tuesday,2025,January
2025-01-08,188.832764,192.550003,193.020004,191.520004,192.960007,436500,Wednesday,2025,January
...,...,...,...,...,...,...,...,...,...
2025-12-23,219.240005,219.240005,219.509995,218.020004,218.880005,330500,Tuesday,2025,December
2025-12-24,216.729996,216.729996,217.029999,215.000000,215.699997,170800,Wednesday,2025,December
2025-12-26,216.619995,216.619995,217.139999,215.949997,216.380005,146000,Friday,2025,December
2025-12-29,216.440002,216.440002,216.669998,214.860001,215.669998,247100,Monday,2025,December
2025-12-30,214.850006,214.850006,216.100006,214.850006,215.880005,184500,Tuesday,2025,December

In [65]:
stocks_df.loc['2014', 'Close'].mean()

np.float64(116.21313506785715)

In [66]:
filt = (stocks_df['Month'] == 'October') | (stocks_df['Month'] == 'November') | (stocks_df['Month'] == 'December') | (stocks_df['Month'] == 'January')

In [67]:
stocks_df.loc[filt, 'Open'].mean()

np.float64(74.92987535845835)

In [68]:
year_grp = stocks_df.groupby('Year')

In [69]:
year_grp['Year'].count()

Year
1980    201
1981    253
1982    253
1983    253
1984    253
1985    252
1986    253
1987    253
1988    253
1989    252
1990    253
1991    253
1992    254
1993    253
1994    252
1995    252
1996    254
1997    253
1998    252
1999    252
2000    252
2001    248
2002    252
2003    252
2004    252
2005    252
2006    251
2007    251
2008    253
2009    252
2010    252
2011    252
2012    250
2013    252
2014    252
2015    252
2016    252
2017    251
2018    251
2019    252
2020    253
2021    252
2022    251
2023    250
2024    252
2025    249
Name: Year, dtype: int64

In [70]:
month_grp = stocks_df.groupby('Month')
month_grp['Month'].count()

Month
April         951
August       1017
December      972
February      863
January       927
July          974
June          980
March         996
May           972
November      937
October      1017
September     936
Name: Month, dtype: int64

In [71]:
stocks_df.resample('MS')['High'].max()

Date
1980-03-01      3.451775
1980-04-01      3.705975
1980-05-01      4.067208
1980-06-01      4.120724
1980-07-01      3.975562
                 ...
2025-08-01    201.800003
2025-09-01    202.869995
2025-10-01    211.240005
2025-11-01    208.320007
2025-12-01    220.559998
Freq: MS, Name: High, Length: 550, dtype: float64

In [72]:
stocks_df.resample('MS').agg({'Close' : 'mean', 'Open' : 'mean', 'High' : 'max', 'Low' : 'min', 'Volume' : 'sum'})

                 Close        Open        High         Low   Volume
Date
1980-03-01    3.336229    3.343527    3.451775    3.291227   153227
1980-04-01    3.420557    3.427565    3.705975    3.237711   379326
1980-05-01    3.853144    3.858878    4.067208    3.665839   219561
1980-06-01    3.973523    3.982697    4.120724    3.750795    64957
1980-07-01    3.741855    3.755265    3.975562    3.652460   100549
...                ...         ...         ...         ...      ...
2025-08-01  192.419049  191.994760  201.800003  177.770004  7091500
2025-09-01  197.989048  197.757620  202.869995  190.729996  5389100
2025-10-01  198.822175  198.544349  211.240005  185.000000  7345400
2025-11-01  201.183157  201.000528  208.320007  191.240005  5138600
2025-12-01  208.229048  207.965715  220.559998  192.710007  6643700

[550 rows x 5 columns]

In [73]:
stocks_df.resample('YS').agg({'Close' : 'mean', 'Open' : 'mean', 'High' : 'max', 'Low' : 'min', 'Volume' : 'sum'})

                 Close        Open        High         Low     Volume
Date
1980-01-01    3.894606    3.902676    4.776293    3.237711    1800314
1981-01-01    5.526536    5.540489    7.866836    3.877226    3311395
1982-01-01    4.906756    4.934149    6.544224    4.017706    1435736
1983-01-01    6.677588    6.702782    8.753962    5.439355    5624637
1984-01-01    7.767911    7.805350    8.838952    6.960675    4492620
1985-01-01    7.460876    7.487435    9.370139    6.692957   12198331
1986-01-01   14.100763   14.142985   21.832424    8.995334   38348420
1987-01-01   19.181008   19.241377   24.737167   14.148910   11310667
1988-01-01   27.977699   28.051808   33.826202   20.989113    6222652
1989-01-01   30.220124   30.321829   32.664307   28.040142    2723318
1990-01-01   25.792596   25.913705   29.855371   21.694216    2539218
1991-01-01   23.721973   23.807627   26.136364   21.022726    3962650
1992-01-01   22.527559   22.560531   25.000000   18.875000    6369500
1993-01-01   29.270257   29.264328   34.875000   21.625000    5677200
1994-01-01   40.320126   40.287822   45.125000   31.750000    4627400
1995-01-01   39.134673   39.102865   42.875000   34.750000    4798700
1996-01-01   47.413632   47.368479   57.875000   41.250000    6069500
1997-01-01   56.363389   56.379570   65.000000   49.750000    7383700
1998-01-01   50.581845   50.470982   59.625000   40.937500    4773400
1999-01-01   62.463418   62.389013   97.375000   45.937500    6335300
2000-01-01   86.141240   86.244752  108.250000   62.759998    5669600
2001-01-01   62.602218   62.549032   75.639999   46.599998    8343900
2002-01-01   52.308294   52.266468   60.000000   45.500000   15076100
2003-01-01   54.065595   53.972302   69.750000   41.169998   30467700
2004-01-01   74.497222   74.473968   82.940002   64.519997   51335000
2005-01-01   81.515754   81.497659  104.900002   70.949997   78816000
2006-01-01  110.615936  110.659044  135.089996   94.519997   94974900
2007-01-01  121.078048  121.173745  138.000000  104.500000  143412900
2008-01-01   90.413636   90.511186  117.589996   55.410000  228167300
2009-01-01   76.050278   76.044365   87.669998   56.790001  185673700
2010-01-01   75.067500   75.079683   91.970001   67.559998  279174700
2011-01-01   76.704325   76.690992   93.900002   60.369999  175290400
2012-01-01   79.816000   79.762960   93.360001   67.269997  104236400
2013-01-01  117.786944  117.710198  134.940002   93.199997  128546700
2014-01-01  116.213135  116.244325  129.300003  103.379997   97065600
2015-01-01  130.025080  130.071349  145.800003  109.070000   77236900
2016-01-01  111.025000  111.054921  123.180000   97.800003   97532400
2017-01-01  114.916414  114.908884  128.440002  103.620003   53030900
2018-01-01  127.655179  127.763466  140.990005  111.120003   50653900
2019-01-01  128.519921  128.483770  145.410004  114.290001   35049300
2020-01-01  131.841067  131.949012  156.300003  108.010002   53918200
2021-01-01  168.670833  168.662182  188.949997  139.289993   71059700
2022-01-01  160.684223  160.851315  213.740005  130.070007   65143900
2023-01-01  159.507080  159.453720  195.649994  132.350006   70570100
2024-01-01  200.998849  201.004126  255.229996  159.039993   84179300
2025-01-01  189.614337  189.514579  220.559998  155.000000   92577900

In [74]:
stocks_df.head()

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month
Date,,,,,,,,,
1980-03-17,1.813283,3.291227,3.344743,3.291227,3.291227,41109,Monday,1980,March
1980-03-18,1.820654,3.304606,3.358122,3.304606,3.304606,9343,Tuesday,1980,March
1980-03-19,1.820654,3.304606,3.304606,3.304606,3.304606,0,Wednesday,1980,March
1980-03-20,1.820654,3.304606,3.358122,3.304606,3.304606,10277,Thursday,1980,March
1980-03-21,1.864881,3.384880,3.438396,3.384880,3.384880,8409,Friday,1980,March

In [76]:
stocks_df.resample('W')['Close'].mean()

Date
1980-03-23      3.317985
1980-03-30      3.358122
1980-04-06      3.264469
1980-04-13      3.315309
1980-04-20      3.446423
                 ...
2025-12-07    197.296002
2025-12-14    200.801999
2025-12-21    215.786002
2025-12-28    218.024998
2026-01-04    215.645004
Freq: W-SUN, Name: Close, Length: 2390, dtype: float64

In [77]:
stocks_df.resample('MS')['Close'].mean()

Date
1980-03-01      3.336229
1980-04-01      3.420557
1980-05-01      3.853144
1980-06-01      3.973523
1980-07-01      3.741855
                 ...
2025-08-01    192.419049
2025-09-01    197.989048
2025-10-01    198.822175
2025-11-01    201.183157
2025-12-01    208.229048
Freq: MS, Name: Close, Length: 550, dtype: float64

In [ ]:
# is the value of the stock increasing every year?

year_grp['Close'].mean().sort_values()

Year
1980      3.894606
1982      4.906756
1981      5.526536
1983      6.677588
1985      7.460876
1984      7.767911
1986     14.100763
1987     19.181008
1992     22.527559
1991     23.721973
1990     25.792596
1988     27.977699
1993     29.270257
1989     30.220124
1995     39.134673
1994     40.320126
1996     47.413632
1998     50.581845
2002     52.308294
2003     54.065595
1997     56.363389
1999     62.463418
2001     62.602218
2004     74.497222
2010     75.067500
2009     76.050278
2011     76.704325
2012     79.816000
2005     81.515754
2000     86.141240
2008     90.413636
2006    110.615936
2016    111.025000
2017    114.916414
2014    116.213135
2013    117.786944
2007    121.078048
2018    127.655179
2019    128.519921
2015    130.025080
2020    131.841067
2023    159.507080
2022    160.684223
2021    168.670833
2025    189.614337
2024    200.998849
Name: Close, dtype: float64

In [ ]:
print("We can clearly infer from the results above that the mean stock close value increases every year, ignoring a few anomalies. ")

We can clearly infer from the results above that the mean stock close value increases every year, ignoring a few anomalies.

In [ ]:
stocks_df['Growth'] = stocks_df['Close'] - stocks_df['Open']

In [100]:
month_grp['Growth'].sum().sort_values(ascending=False)

Month
November     34.611831
April         6.967611
December     -6.865982
February     -9.338487
October     -10.912745
September   -15.932923
July        -18.423271
January     -20.404318
May         -22.729466
August      -23.956510
March       -35.036124
June        -38.928584
Name: Growth, dtype: float64

In [101]:
print("It is evident that the stock grows most in the month of november and april.")

It is evident that the stock grows most in the month of november and april.

In [110]:
def analyse_year(year):
    max_price = year_grp['High'].max().loc[year]
    min_price = year_grp['Low'].min().loc[year]
    avg_growth = year_grp['Growth'].mean().loc[year]
    avg_close = year_grp['Close'].mean().loc[year]

    return_statement = "The analysis for the year {} is as following:\n1. Highest Stock Price = {}\n2. Lowest Stock Price = {}\n3. Average Growth = {}\n4. Average Close Price = {}".format(year, max_price, min_price, avg_growth, avg_close)

    return return_statement

In [112]:
print(analyse_year(2020))

The analysis for the year 2020 is as following:
1. Highest Stock Price = 156.3000031
2. Lowest Stock Price = 108.0100021
3. Average Growth = -0.10794450395256965
4. Average Close Price = 131.84106725652174

In [114]:
stocks_df.loc['2015'] # gives data of year 2015

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month,Growth
Date,,,,,,,,,,
2015-01-02,93.269127,125.669998,126.639999,124.889999,126.230003,250000,Friday,2015,January,-0.560005
2015-01-05,91.562134,123.370003,124.610001,123.050003,124.440002,240600,Monday,2015,January,-1.070000
2015-01-06,90.619560,122.099998,123.720001,121.209999,123.400002,285600,Tuesday,2015,January,-1.300003
2015-01-07,92.898033,125.169998,126.059998,125.059998,125.519997,385700,Wednesday,2015,January,-0.349998
2015-01-08,94.686684,127.580002,127.699997,126.449997,126.449997,498800,Thursday,2015,January,1.130005
...,...,...,...,...,...,...,...,...,...,...
2015-12-24,95.993073,125.769997,126.110001,125.400002,125.400002,102300,Thursday,2015,December,0.369995
2015-12-28,95.000847,124.470001,124.849998,124.230003,124.430000,283800,Monday,2015,December,0.040001
2015-12-29,95.222191,124.760002,125.080002,124.089996,124.089996,160400,Tuesday,2015,December,0.670006
2015-12-30,94.046799,123.220001,124.430000,123.110001,124.400002,334100,Wednesday,2015,December,-1.180000
2015-12-31,93.909409,123.040001,124.330002,122.650002,123.349998,221000,Thursday,2015,December,-0.309998

In [116]:
stocks_df.loc['2015-01'] # give data of 2015 jan

,Adj_Close,Close,High,Low,Open,Volume,Day,Year,Month,Growth
Date,,,,,,,,,,
2015-01-02,93.269127,125.669998,126.639999,124.889999,126.230003,250000,Friday,2015,January,-0.560005
2015-01-05,91.562134,123.370003,124.610001,123.050003,124.440002,240600,Monday,2015,January,-1.070000
2015-01-06,90.619560,122.099998,123.720001,121.209999,123.400002,285600,Tuesday,2015,January,-1.300003
2015-01-07,92.898033,125.169998,126.059998,125.059998,125.519997,385700,Wednesday,2015,January,-0.349998
2015-01-08,94.686684,127.580002,127.699997,126.449997,126.449997,498800,Thursday,2015,January,1.130005
2015-01-09,93.573418,126.080002,127.769997,125.980003,127.769997,150300,Friday,2015,January,-1.689995
2015-01-12,93.543732,126.040001,127.739998,125.339996,126.500000,306700,Monday,2015,January,-0.459999
2015-01-13,93.818344,126.410004,127.870003,125.629997,127.050003,252900,Tuesday,2015,January,-0.639999
2015-01-14,93.380447,125.820000,125.980003,124.629997,125.419998,363800,Wednesday,2015,January,0.400002
2015-01-15,94.092941,126.779999,128.369995,126.629997,127.870003,310400,Thursday,2015,January,-1.090004
2015-01-16,95.651512,128.880005,129.000000,128.050003,128.320007,441600,Friday,2015,January,0.559998
2015-01-20,95.859314,129.160004,129.789993,128.759995,129.500000,436700,Tuesday,2015,January,-0.339996
2015-01-21,95.488220,128.660004,128.820007,128.009995,128.360001,606700,Wednesday,2015,January,0.300003
2015-01-22,96.378838,129.860001,130.229996,127.959999,128.970001,235500,Thursday,2015,January,0.889999
2015-01-23,96.230392,129.660004,130.210007,129.500000,130.000000,292900,Friday,2015,January,-0.339996
2015-01-26,97.863190,131.860001,132.309998,130.979996,130.979996,350600,Monday,2015,January,0.880005
2015-01-27,97.299141,131.100006,131.729996,130.880005,131.130005,301000,Tuesday,2015,January,-0.029999
2015-01-28,97.187805,130.949997,132.419998,130.699997,132.229996,304100,Wednesday,2015,January,-1.279999
2015-01-29,98.078423,132.149994,132.179993,130.940002,131.479996,411800,Thursday,2015,January,0.669998
2015-01-30,95.629242,128.850006,129.979996,128.690002,129.490005,273900,Friday,2015,January,-0.639999