In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [5]:
df.dropna() # this drops the rows with missing values

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [6]:
df.dropna(axis=0, how='any') # these are the default arguements, we can edit them.

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [7]:
df.dropna(axis=0, how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [8]:
df.dropna(subset=['email']) #only rows with missing emails are dropped

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [9]:
#remember custom missing values like NA and Missing are not caught by dropna, smth else is done to take care of them

In [10]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6  False  False  False  False

In [11]:
df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [12]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [13]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [14]:
df['age'] = df['age'].astype(float)

In [15]:
df['age'].mean()

np.float64(46.75)

In [16]:
type(df['age'][0])

numpy.float64